# DX12 셰이더 컴파일 대상 목록.
# 신규 .hlsl이 생기면 여기에 add_dx_shader() 호출을 한 줄 추가한다. (문법: ShaderCompile.cmake 참조)

add_dx_shader(ForwardOpaque       STAGES VS PS)
add_dx_shader(ForwardTransparent  STAGES VS PS)
add_dx_shader(OITComposite        STAGES VS PS)
add_dx_shader(AnimationDemo       STAGES VS PS)
add_dx_shader(Sky                 STAGES VS PS)
add_dx_shader(Glyph               STAGES VS PS)
add_dx_shader(DebugLine           STAGES VS PS)
add_dx_shader(HelloCompute        STAGES CS)
add_dx_shader(BonePaletteCompute  STAGES CS)
add_dx_shader(GBuffer             STAGES VS PS)
add_dx_shader(DeferredLighting    STAGES CS)
add_dx_shader(Blit                STAGES VS PS)
add_dx_shader(GBufferSkinned      STAGES VS PS)
add_dx_shader(ShadowMap           STAGES VS PS NO_COMMON)
add_dx_shader(ShadowMapSkinned    STAGES VS PS NO_COMMON)
add_dx_shader(IrradianceConvolve  STAGES CS)
add_dx_shader(PrefilterSpecular   STAGES CS)
add_dx_shader(IntegrateBRDF       STAGES CS)
add_dx_shader(SSAO                STAGES VS PS)
add_dx_shader(SSAOBlur            STAGES VS PS)
add_dx_shader(Bloom_BrightPass    STAGES VS PS NO_COMMON)
add_dx_shader(Bloom_BlurH         STAGES VS PS NO_COMMON)
add_dx_shader(Bloom_BlurV         STAGES VS PS NO_COMMON)
add_dx_shader(Bloom_Composite     STAGES VS PS NO_COMMON)
